baseURL = 'https://movedeveloper.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'github-style'

pygmentsCodeFences = true
pygmentsUseClasses = true


[params]
    author = "Hao H."
    description = ""
    github = "movedeveloper"
    email = "kzdmxqatgmaildotcom"
    url = "https://movedeveloper.github.com"
    keywords = "blog, google analytics"
    rss = false
    lastmod = true
    userStatusEmoji = ""
    favicon = "/images/github.png"
    avatar = "/images/avatar.jpeg"
    headerIcon = "/images/github-mark-white.png"
    location = "Vietnam"
    enableGitalk = false 


[frontmatter]
    lastmod = ["lastmod", ":fileModTime", ":default"]

[services]
    [services.googleAnalytics]
        ID = ""