baseURL = 'https://movedeveloper.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'github-style'

pygmentsCodeFences = true
pygmentsUseClasses = true


[params]
    author = "Hao H."
    description = ""
    github = "movedeveloper"
    email = "kzdmxq@gmail.com"
    url = "https://movedeveloper.github.com"
    keywords = "blog, google analytics"
    rss = true
    lastmod = true
    userStatusEmoji = ""
    favicon = "/images/github.png"
    avatar = "/images/avatar.jpeg"
    headerIcon = "/images/GitHub-Mark-Light-32px.png"
    location = "Vietnam"
    enableGitalk = false 

    [params.gitalk]
        clientID = "Your client ID"
        clientSecret = "Your client secret"
        repo = "repo"
        owner = "MeiK2333"
        admin = "MeiK2333"
        id = "location.pathname"
        labels = "gitalk"
        perPage = 15
        pagerDirection = "last"
        createIssueManually = true
        distractionFreeMode = false

    [[params.links]]
        title = "Link"
        href = "https://github.com/movedeveloper"
    [[params.links]]
        title = "Link2"
        href = "https://meik2333.com"
        icon = "https://meik2333.com/images/avatar.png"

[frontmatter]
    lastmod = ["lastmod", ":fileModTime", ":default"]

[services]
    [services.googleAnalytics]
        ID = "UA-123456-789"